### ISSUE TITLE
启动和打包问题

### ISSUE THREAD

**Issue by yanbowe** [HuaSakura/electron-vite-pro#1]
![image](https://github.com/user-attachments/assets/3a576f87-cad6-43e2-ad47-f3ab00eaffc6)
执行pnpm serve就直接结束了，没有启动客户端

**Comment by yanbowe** [comment]
![image](https://github.com/user-attachments/assets/53740847-6630-45aa-91e1-4d219283d9d0)
执行pnpm build无法打包成功

**Comment by HuaSakura** [comment]
> ![图像](https://private-user-images.githubusercontent.com/43030980/364615823-53740847-6630-45aa-91e1-4d219283d9d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MTYxNjMsIm5iZiI6MTcyNTUxNTg2MywicGF0aCI6Ii80MzAzMDk4MC8zNjQ2MTU4MjMtNTM3NDA4NDctNjYzMC00NWFhLTkxZTEtNGQyMTkyODNkOWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDA1NTc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMjExYzRhMzI2MjJjOGY2MDc5NDFkZjc3ZjM5Y2ExNGFhMDIzZTFlMjFlMDJiMTRkMDU0NjhlZjMzMjkzM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.977eHuU5wQF6RNjtyw7w0-nQserZRo6XYWbw5w_We1Y) 执行pnpm build无法成功

必须开启梯子并把终端挂载到梯子的代理上才可以，因为electron的资源在外网，第一次打包时需要拉取打包资源，后续的打包就不需要了

**Comment by HuaSakura** [comment]
> ![图像](https://private-user-images.githubusercontent.com/43030980/364615196-3a576f87-cad6-43e2-ad47-f3ab00eaffc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MTYyNzUsIm5iZiI6MTcyNTUxNTk3NSwicGF0aCI6Ii80MzAzMDk4MC8zNjQ2MTUxOTYtM2E1NzZmODctY2FkNi00M2UyLWFkNDctZjNhYjAwZWFmZmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDA1NTkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZWQ4ZjM1OWUwNjA5MTMzM2U2ZDUyMjRiNGNiYjk3ZDdkNmQyMDMwMmRhYjgzMmNlMWM0MDgxOTExNTlmNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cy5yPjA4H99S_mp7uldJ2e1_1B560atszoLL0eDA_QU) 执行pnpmserve就直接结束了，没有启动客户端

我这边使用的是yarn，由于electron的资源情况，没有使用国内的源，你这可以尝试使用npm进行初始，在初始化时，需要终端挂载梯子代理

**Comment by HuaSakura** [comment]
此项目暂时只在win下执行过，没有Mac，不清楚在Mac环境下的运行情况

**Comment by yanbowe** [comment]
好的
